[REC-101] - Receptkártyák, és keresés frontend élretrekeltése backend-es adatokkal.
progmatic-fs-2023/receptkiraly pull request #94
Opened 2024-01-24 22:38 UTC by jakobszengabor

Home Page-en és a Search Page-en a "Modal functions" és a "stateObject" és a hozzá tartozó statek keltik életre a modal komponensbe beágyazott DetailedRecipe kártyát. Ezeket jó lenne egy külön komponensbe tenni, nekem egyenlőre nem nagyon sikerült.

A detailedRecipe-hez az adatokat az openModal függvény fetcheli le amikor megnyitjuk az adott recipeCard-hoz tartozó kártyát.

A Search Page a filterek segítségével használható. Az oldalon a linkekben elhelyezett kulcs érték párok segítségével küldök egy requested a backend felé.

A navigáció attól függ hogy 3000-es vagy 5173-as porton vagyunk állítja be a linkeket a navigáció gombokhoz. Tehát mind1, hogy a builden vagyunk vagy máshol.

A navigáció mappában helyeztem el a labels, meals, beverages, desserts tömböket. Elméletileg mindenhol onnan mappalek ki. Minden onnan szedi az adatokat.

2024-01-25 17:03 UTC, MKORTVELYESS requested changes

2024-01-25 17:03 UTC, MKORTVELYESS commented on client/src/pages/SearchRecipes.jsx
> +            imgUrl={`http://localhost:3000/${recipe.img}`}
url

2024-01-25 22:13 UTC, jakobszengabor commented on client/src/pages/Home.jsx
> +      const response = await fetch(`http://localhost:3000/api/recipes/${id}`);
Kijavítva!

2024-01-25 22:13 UTC, jakobszengabor commented on client/src/pages/Home.jsx
> +                      imgUrl={`http://localhost:3000/${recipe.img}`}
Kijavítva!

2024-01-25 22:14 UTC, jakobszengabor commented on client/src/pages/SearchRecipes.jsx
> +            imgUrl={`http://localhost:3000/${recipe.img}`}
Kijavítva!

2024-01-26 23:20 UTC, closed without merging

2024-01-26 23:21 UTC, jakobszengabor commented
Csináltam egy újabb verziót. A biztonság kedvéért egy REC-101v2 nevű branchen.