Rec 165
progmatic-fs-2023/receptkiraly pull request #98
Opened 2024-01-26 13:53 UTC by katonabalint13

2024-01-26 16:56 UTC, MeetAlica requested changes

2024-01-26 16:56 UTC, MeetAlica commented on client/src/pages/Home.jsx
> +  const editMode = true;
szerintem én ezt a sort kivenném

2024-01-26 16:56 UTC, MeetAlica commented on client/src/pages/Home.jsx
> +                        <DetailedRecipe editMode={editMode} />
és ide propba csak annyit írnék, hogy editMode (shortcut to editMode = true)

2024-01-27 08:27 UTC, MKORTVELYESS approved these changes

2024-01-27 08:28 UTC, MKORTVELYESS approved these changes

2024-01-27 08:28 UTC, MKORTVELYESS approved these changes

2024-01-27 08:29 UTC, merged